mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth.views import (
    # login_view,
    get_cookie_view, set_cookie_view,
    get_session_view, set_session_view,
    MyLogoutView, AboutMeView, RegisterView, FooBarView, ProfileUpdateView
)


app_name = 'myauth'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/update/<int:pk>', ProfileUpdateView.as_view(), name='profile_update'),

    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path('accounts/', set_session_view, name='session-set'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

mysite/shopapp/urls.py
from django.urls import path
from .views import (
    ShopIngexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrdersDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    CreateOrderView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
)

app_name = 'shopapp'

urlpatterns = [
    path('', ShopIngexView.as_view(), name='index'),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>', OrdersDetailView.as_view(), name='order_details'),
    path('orders/create/', CreateOrderView.as_view(), name='order_create'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
]

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from myauth.models import Profile


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):

    class Meta:
        ordering = ['name', 'price']

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self) -> str:
        return f'Product(pk={self.pk}, name={self.name!r})'


def product_image_directory_path(instance: "ProductImage", filename: str) -> str:
    return 'products/product_{pk}/images/{filename}'.format(
        pk=instance.product.pk,
        filename=filename,
    )

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_image_directory_path)
    description = models.CharField(max_length=200, null=True, blank=True)


class Order(models.Model):
    class Meta:
        ordering = ['user', 'delivery_address']

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

    def __str__(self) -> str:
        return f'Order(products={self.pk}, delivery_address={self.delivery_address!r})'

mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm, ImageField, ClearableFileInput

from .models import Product, Order


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'discount', 'description', 'preview'

    images = ImageField(
        widget=ClearableFileInput(attrs={'multiple': True}),
    )




class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address', 'promocode', 'user', 'products'

mysite/shopapp/views.py
from timeit import default_timer

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order, ProductImage


class ShopIngexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products
        }
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/products-details.html'
    model = Product
    queryset = Product.objects.prefetch_related('images')
    context_object_name = 'product'


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(UserPassesTestMixin, CreateView):
    permission_required = 'add_product'
    model = Product
    # fields = 'name', 'price', 'discount', 'description', 'preview'
    # success_url = reverse_lazy('shopapp:products_list')
    form_class = ProductForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.user_permissions



class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    template_name_suffix = '_update_form'
    permission_required = 'product_update'
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={'pk': self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist('images'):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )

        return response

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        product = self.get_object()
        permissions = self.request.user.get_all_permissions()
        return ('shopapp.change_product' in permissions) \
            and (product.created_by.pk == self.request.user.pk)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (Order.objects.
                select_related('user').
                prefetch_related('products'))


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    queryset = (Order.objects.
                select_related('user').
                prefetch_related('products'))


class CreateOrderView(CreateView):
    template_name = 'shopapp/order_form.html'
    queryset = (Order.objects.
                select_related('user').
                prefetch_related('products'))
    fields = 'delivery_address', 'promocode', 'user', 'products'
    success_url = reverse_lazy('shopapp:orders_list')


class OrderUpdateView(UpdateView):
    template_name = 'shopapp/order_update_form.html'
    queryset = (Order.objects.
                select_related('user').
                prefetch_related('products'))
    fields = 'delivery_address', 'promocode', 'user', 'products'
    # success_url = reverse_lazy('shopapp:order_details')

    def get_success_url(self):
        return reverse(
            'shopapp:order_details',
            kwargs={'pk': self.object.pk}
        )


class OrderDeleteView(DeleteView):
    template_name = 'shopapp/order_confirm_delete.html'
    queryset = (Order.objects.
                select_related('user').
                prefetch_related('products'))
    success_url = reverse_lazy('shopapp:orders_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by('pk').all()
        products_data = [
            {
                'pk': product.pk,
                'name': product.name,
                'price': product.price,
                'archived': product.archived,
            }
            for product in products
        ]
        return JsonResponse({'products': products_data})


# def create_order(request: HttpRequest) -> HttpResponse:
#     if request.method == 'POST':
#         form = OrderForm(request.POST)
#         if form.is_valid():
#             form.save()
#             url = reverse('shopapp:orders_list')
#             return redirect(url)
#     else:
#         form = OrderForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'shopapp/create-order.html', context)

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
    Base Body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday}}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new form</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new form</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>
    
    <div>
        <a href="{% url 'shopapp:products_list' %}"
            >Back to products</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Group list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        {% if not groups %}
        <h3>No groups yet</h3>
    {% else %}
        <ul>
            {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <div>
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>{{ permission.name }}
                                (<code>{{ permission.codename }}</code>)
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
            {% endfor %}

        </ul>

    {% endif %}
    </div>


{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete order
{% endblock %}

{% block body %}
    <h1>Are you sure to want to delete order?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order #{{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Deleted</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>

    <div>
        <p>Order by {% firstof object.user.first_name order.user.username %}</p>
        <p>Promocode: <code>{{ object.promocode }}</code></p>
        <p>Delivery address: {{ object.delivery_address }}</p>
        <div>
            Products in order:
            <ul>
                {% for product in object.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                {% endfor %}

            </ul>
        </div>
    </div>

    <div>
        <a href="{% url 'shopapp:order_update' pk=order.pk%}">Update order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:order_delete' pk=order.pk%}">Delete order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create new order
{% endblock %}

{% block body %}
    <h1>Create newest order now</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create order</button>
        </form>
    </div>
    
    <div>
        <a href="{% url 'shopapp:orders_list' %}"></a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'shopapp:products_list' %}">Go to products list</a>
    </div>
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                    <p><a href="{% url 'shopapp:order_details' pk=order.pk%}"
                    >Order details #{{ order.pk }}</a></p>
                    <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promocode: <code>{{ order.promocode }}</code></p>
                    <p>Delivery address: {{ order.delivery_address }}</p>
                    <div>
                        Products in order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} for ${{ product.price }}</li>
                            {% endfor %}

                        </ul>
                    </div>

                </div>
            {% endfor %}

        </div>
    {% else %}
        <h3>No objects yet</h3>
    {% endif %}
    
    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Order
{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update order</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk %}"
        >Back to order #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archived product
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archived product?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archived</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>
    
    <div>
        <a href="{% url 'shopapp:products_list' %}"
            >Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
        <div>Created by: {{ product.created_by_id }}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        <h3>Images:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>No images upload yet</div>
            {% endfor %}
            
        </div>
    </div>
    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Go to orders list</a>
    </div>
    {% if perms.shopapp.add_product %}
        <div>
            <a href="{% url 'shopapp:product_create' %}">
                Create a new product
            </a>
        </div>
    {% endif %}

    <h1>Products:</h1>
    {% if products %}
        <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
                >Name:{{ product.name }}</a></p>
                <p>Price: {{ product.price }}</p>
                <p>Discount: {% firstof product.discount 'no discount' %}</p>
                <p>Created_by_user_id: {{ product.created_by}}</p>
            </div>
        
        {% endfor %}
        
        </div>
    {% else %}
        <h3>No products yet</h3>
    {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock %}


{% block body %}
    <h1>
        Hello Shop Index
    </h1>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} ({{ name|length }}) for $ {{ price }}</li>
                {% if name|length_is:'7' %}
                    <span>Lucky Product</span>

                {% endif %}
            {% empty %}
                No products here
            {% endfor %}
        </ul>
    </div>
    <div>
        Time running: {{ time_running }}
    </div>

    <div>
        {% lorem 3 p random %}
    </div>

{% endblock %}