mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth.views import (
    # login_view,
    get_cookie_view, set_cookie_view,
    get_session_view, set_session_view,
    MyLogoutView, AboutMeView, RegisterView, FooBarView, ProfileUpdateView
)


app_name = 'myauth'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/update/<int:pk>', ProfileUpdateView.as_view(), name='profile_update'),

    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path('accounts/', set_session_view, name='session-set'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

mysite/shopapp/urls.py
from django.urls import path
from .views import (
    ShopIngexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrdersDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    CreateOrderView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
)

app_name = 'shopapp'

urlpatterns = [
    path('', ShopIngexView.as_view(), name='index'),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>', OrdersDetailView.as_view(), name='order_details'),
    path('orders/create/', CreateOrderView.as_view(), name='order_create'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
]

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User


def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return 'profiles/profile_{pk}/avatar/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=100, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_directory_path)


def profile_image_directory_path(instance: "ProfileImage", filename: str) -> str:
    return 'profiles/profile_{pk}/images/{filename}'.format(
        pk=instance.profile.pk,
        filename=filename,
    )

class ProfileImage(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=profile_image_directory_path)
    description = models.CharField(max_length=200, null=True, blank=True)

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from myauth.models import Profile


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):

    class Meta:
        ordering = ['name', 'price']

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self) -> str:
        return f'Product(pk={self.pk}, name={self.name!r})'


def product_image_directory_path(instance: "ProductImage", filename: str) -> str:
    return 'products/product_{pk}/images/{filename}'.format(
        pk=instance.product.pk,
        filename=filename,
    )

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_image_directory_path)
    description = models.CharField(max_length=200, null=True, blank=True)


class Order(models.Model):
    class Meta:
        ordering = ['user', 'delivery_address']

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

    def __str__(self) -> str:
        return f'Order(products={self.pk}, delivery_address={self.delivery_address!r})'

mysite/myauth/forms.py
from django import forms
from django.forms import ImageField, ClearableFileInput

from myauth.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

    images = ImageField(
            widget=ClearableFileInput(attrs={'multiple': True}),
        )

mysite/myauth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from django.forms.forms import BaseForm
from django.shortcuts import reverse

from myauth.forms import ProfileForm
from myauth.models import Profile, ProfileImage


# class AboutMeView(DetailView):
    # template_name = 'myauth/about-me.html'
    # model = User
    # context_object_name = 'user_profile'
class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class ProfileUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'myauth/profile_update_form.html'
    model = Profile
    fields = 'avatar', 'bio'

    def test_func(self):
        return self.request.user.id == self.request.user.profile.id or \
            self.request.user.is_superuser or \
            self.request.user.is_staff

    def get_success_url(self):
        return reverse('myauth:about-me')


# class ProfileUpdateView(UserPassesTestMixin, UpdateView):
#     model = Profile
#     template_name_suffix = '_update_form'
#     permission_required = 'change_profile'
#     form_class = ProfileForm
#     context_object_name = 'user_profile'
#
#     def get_success_url(self):
#         return reverse(
#             'myauth:about-me',
#             # kwargs={'pk': self.object.pk}
#         )
#
#     def form_valid(self, form):
#         response = super().form_valid(form)
#         for image in form.files.getlist('images'):
#             ProfileImage.objects.create(
#                 profile=self.object,
#                 image=image,
#             )
#         return response
#
#     def test_func(self):
#         if self.request.user.is_superuser:
#             return True
#
#         profile = self.get_object()
#         permissions = self.request.user.get_all_permissions()
#         return ('myauth.change_profile' in permissions) \
#             and (profile.pk == self.request.user.pk)


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request,
                            username=username,
                            password=password,)
        login(request=self.request, user=user)
        return response


@user_passes_test(lambda u: u.is_superuser)  # Эта проверка может увести в цикл, т.к. там редирект на авторизацию
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f'Cookie value {value!r}')


@permission_required('myauth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set!')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default')
    return HttpResponse(f'Session value: {value!r}')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About user
{% endblock %}

{% block body %}
    <p>
        <a href="{% url 'shopapp:products_list' %}">Go to products list</a>
    </p>
    <p>
        <a href="{% url 'shopapp:orders_list' %}">Go to orders list</a>
    </p>
    <h1>Info about user</h1>
    {% if user.is_authenticated %}
        <h2>Detail</h2>
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.name }}">
        {% else %}
            No avatar yet
        {% endif %}

        <p>ID: {{ user.pk }}</p>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>

        <h3>Images:</h3>
        <div>
            {% for img in user.profile.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>No images upload yet</div>
            {% endfor %}
        </div>

        <div>
            <button>
                <a href="{% url 'myauth:profile_update' pk=user.pk %}">
                Update profile
            </a>
            </button>
        </div>
    {% else %}
        <h2>User is anonimus</h2>
    {% endif %} 
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    
    {% endblock %}</title>
</head>
<body>
    {% block body %}
    
    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}

    <form method="post">
        {% csrf_token %}

        {{ form.as_p}}

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}


{% block title %}
    Profile update
{% endblock %}

{% block body %}
    <h1>Update profile</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update profile</button>
    </form>
    
    <div>
        <a href="{% url 'myauth:about-me' %}">
            Back to about me #{{ profile.pk }}
        </a>
    </div>

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/users_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Go to orders list</a>
    </div>
    {% if perms.shopapp.add_product %}
        <div>
            <a href="{% url 'shopapp:product_create' %}">
                Create a new product
            </a>
        </div>
    {% endif %}

    <h1>Products:</h1>
    {% if products %}
        <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
                >Name:{{ product.name }}</a></p>
                <p>Price: {{ product.price }}</p>
                <p>Discount: {% firstof product.discount 'no discount' %}</p>
                <p>Created_by_user_id: {{ product.created_by}}</p>

                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>
        
        {% endfor %}
        
        </div>
    {% else %}
        <h3>No products yet</h3>
    {% endif %}

{% endblock %}